# Generated by Django 5.0 on 2023-12-22 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wafidlink_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBookinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10000)),
                ('city', models.CharField(max_length=10000)),
                ('country_traveling_to', models.CharField(max_length=10000)),
                ('nationality', models.CharField(max_length=10000)),
                ('visa_type', models.CharField(max_length=10000)),
                ('email_id', models.CharField(max_length=10000)),
                ('phone_no', models.CharField(max_length=10000)),
                ('position_applied_for', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('passport', models.IntegerField()),
                ('agent_name', models.CharField(max_length=1000)),
                ('medical_name', models.CharField(max_length=1000)),
                ('pay_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10000)),
                ('city', models.CharField(max_length=10000)),
                ('country_traveling_to', models.CharField(max_length=10000)),
                ('first_name', models.CharField(max_length=10000)),
                ('last_name', models.CharField(max_length=10000)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=10000)),
                ('gender', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=10000)),
                ('passport_issue_date', models.DateField()),
                ('passport_issue_place', models.CharField(max_length=1000)),
                ('passport_expiry_date', models.DateField()),
                ('visa_type', models.CharField(max_length=10000)),
                ('email_id', models.CharField(max_length=10000)),
                ('phone_no', models.CharField(max_length=10000)),
                ('position_applied_for', models.CharField(max_length=1000)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
            ],
        ),
    ]
