# Generated by Django 5.0 on 2023-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='city',
            field=models.CharField(default='Dhaka', max_length=10000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=10000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='country_traveling_to',
            field=models.CharField(default='Saudi Arabia', max_length=10000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='email_id',
            field=models.CharField(default='nurtravels24@gmail.com', max_length=10000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='nationality',
            field=models.CharField(default='Bangladeshi', max_length=10000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='phone_no',
            field=models.CharField(default='+8800000006030', max_length=10000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='position_applied_for',
            field=models.CharField(default='Worker', max_length=1000),
        ),
        migrations.AlterField(
            model_name='defaultbookininfo',
            name='visa_type',
            field=models.CharField(default='Work Visa', max_length=10000),
        ),
    ]
