# Generated by Django 5.0 on 2023-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_bookinginfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
