# Generated by Django 5.0 on 2023-12-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passport',
            field=models.CharField(max_length=100),
        ),
    ]
