# Generated by Django 5.0 on 2024-01-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtPayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
            ],
        ),
    ]
